. ".\src\database.ps1"
. ".\test\_globals.ps1"

Describe "Backup-Database" {
	if ((Test-Path $TempBackupDir) -eq $true) {
		Remove-Item $TempBackupDir -Force -Recurse | out-null
	}
  
	Context "When BackupFileName parameter is specified" {
		New-Item $TempBackupDir -Type Directory | out-null
		
		Backup-Database `
		-SqlServer "(local)" `
		-DatabaseName $DatabaseToBackup `
		-BackupDirectory $TempBackupDir `
		-BackupFileName "test.bak"

		It "Backs up the database to a file with specified filename" {
			$backupFileExists = Test-Path "$TempBackupDir\test.bak"
		  
			$backupFileExists | Should Be $true
		}
    }
	
	Context "When BackupFileName parameter is not specified" {
  	
		if ((Test-Path $TempBackupDir) -eq $true) {
			Remove-Item $TempBackupDir -Force -Recurse | out-null
		}	
		New-Item $TempBackupDir -Type Directory | out-null
    
		Backup-Database `
			-SqlServer "(local)" `
			-DatabaseName $DatabaseToBackup `
			-BackupDirectory $TempBackupDir
		
		It "Backs up the database to a file with autogenerated filename" {
			Get-Item "$TempTestFolder\$DatabaseToBackup_*.bak"
				$files = @() + (Get-ChildItem $TempBackupDir)
				$files.Length | Should Be 1
			}
		}	
}
